name: Build and deploy

on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_token }}
      - name: Determine tag
        id: determine_tag
        run: |
          if [ -n github.event.release.tag_name ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: irealworlds/tempradar-sensor-api:${{ steps.determine_tag.outputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - docker
    steps:
      - name: Trigger CircleCI Pipeline
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
        env:
          CCI_TOKEN: ${{ secrets.CIRCLECI_API_TOKEN }}
